### ISSUE TITLE
Is it just me or is the ChatBox interfering with the OpenPeripheral Glasses again?

### ISSUE THREAD

**Issue by Selim042** [theoriginalbit/MoarPeripherals#26]
I tried disabling the ChatBox then afterwards, but it still won't get the command.
Additional suggestion: Stop pulling chat commands prefixed with "$$" if ChatBoxes are disabled.

**Comment by theoriginalbit** [comment]
I can't just "stop pulling" chat events at will. The problem is probably to do with the way I handle the events once I have a match.

Previously the ChatBoxes were able to receive any `$$` events that people sent, even though they didn't appear in chat; the changes that I made stopped ChatBoxes from queueing these events to the computer.

I admit however that clearly the logic I used to do that may be flawed, so I'll take a look at this (probably in my lunch break) and see what I can throw together to fix this issue.

**Comment by Selim042** [comment]
Thanks!

**Comment by theoriginalbit** [comment]
This should be fixed now, though I'll just get you @Selim042 to test the [latest build](http://thatcraniumguy.net:8081/job/MoarPeripherals%20for%20Minecraft%201.7/) for me please and let me know.

**Comment by Selim042** [comment]
All I did to test was throw down a comptuer, chatbox, and glasses terminal, but it seems to work now!  Thanks!

**Comment by theoriginalbit** [comment]
Thank you. I don't have OpenPeripheral installed in my development environment, all I have installed are things that my mod is compatible with.

**Comment by Selim042** [comment]
Ahh
