### ISSUE TITLE
Computerraft Mounts

### ISSUE THREAD

**Issue by theoriginalbit** [theoriginalbit/MoarPeripherals#50]
When unmounting ComputerCraft states that we didn't mount the location. performing a mount before unmounting should trick ComputerCraft into thinking we do own the mount; because we do!

**Comment by SquidDev** [comment]
Any progress on this? I'm having an issue with MoarPeripherals/CCTweaks interaction because of this - the peripheral detach gets run on the main thread when unloading chunks (though this is the same behaviour as normal CC networks). Consequently the detach isn't wrapped in a try-catch, and so the exception thrown crashes the game.

**Comment by theoriginalbit** [comment]
I never had issues with this. I was never able to replicate it either. Also don't know of any peripheral mods which wrap their detach in a try-catch.

**Comment by SquidDev** [comment]
See SquidDev-CC/CC-Tweaks#59 and SquidDev-CC/CC-Tweaks#66. If I recall correctly, you can reproduce by placing down two chatboxes next to a computer, then breaking the first and then the second.
